-------------------------------------------------------------------------------
Test set: wl.seckill.dao.cache.RedisDaoTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.421 s <<< FAILURE! - in wl.seckill.dao.cache.RedisDaoTest
redisLogic(wl.seckill.dao.cache.RedisDaoTest)  Time elapsed: 1.325 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [D:\Users\bsx\workspace-IJ\web\seckill\target\classes\mapper\SeckillDao.xml]
### The error may involve wl.seckill.dao.SeckillDao.queryById
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at wl.seckill.dao.cache.RedisDaoTest.redisLogic(RedisDaoTest.java:35)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [D:\Users\bsx\workspace-IJ\web\seckill\target\classes\mapper\SeckillDao.xml]
### The error may involve wl.seckill.dao.SeckillDao.queryById
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at wl.seckill.dao.cache.RedisDaoTest.redisLogic(RedisDaoTest.java:35)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at wl.seckill.dao.cache.RedisDaoTest.redisLogic(RedisDaoTest.java:35)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at wl.seckill.dao.cache.RedisDaoTest.redisLogic(RedisDaoTest.java:35)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at wl.seckill.dao.cache.RedisDaoTest.redisLogic(RedisDaoTest.java:35)

